version: "3.7"

# For local development, only database is running
#
# docker-compose up -d
# uvicorn app.main:app --reload
#

services:
  database:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ./database_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DEFAULT_DATABASE_PORT}:5432"

